### ISSUE TITLE
Add parameters of deeptools to the configuration file

### ISSUE THREAD

**Issue by JihedC** [JihedC/Snakemake_ATAC_2020#2]
Deeptools has a lot of arguments, such as the bin size or the smoothlength. 
All argument need to be included in the configuration file so that we can modify the parameters easily

**Comment by WJH58** [comment]
@JihedC The parameters that I think are necessary have been added to each deeptool.

**Comment by JihedC** [comment]
Ok. Can you elaborate a bit more? Which parameters do you think are necessary? What are the default value? Where were the modification done ? Can you add a commit number?

**Comment by WJH58** [comment]
@JihedC 

bamPEFragmentSize:
binSize: "1000" #This is default value.
numberOfProcessors: "10" #Grant 10 processors to make it run faster.
plotFileFormat: "pdf" # pdf has higher resolution than png.
samplesLabel: "sample1 sample2 sample3 sample4" # I used some general labels here.
plotTitle: "'Fragment size of PE ATAC-seq data'" # This is a general title.

plotCorrelation:
  corMethod: "spearman" # I chose spearman method to plot Correlation because spearman is a non-parametric measure.
  whatToPlot: "heatmap" # the user can also change it to scatter plot.

plotProfile:
  dpi: "100"
  colors: "red blue yellow green" # define colors of profile.

plotHeatmap:
  dpi: "100"
  yMin: "0"
  yMax: "50" # define minimum and maximum value of y axis
  refPointLabel: "TSS" # define the reference point label. By default it's "TSS".
  colorList: "'white, blue'" # define colors of heatmap.

**Comment by JihedC** [comment]
That's much better.
Could you provide in comments the other options for arguments that can take multiple option? 
For example refPointLabel can also be #center

**Comment by WJH58** [comment]
@JihedC I pushed a new config.yaml to dev branch. Apart from the comments above, I added more comments:

bamCoverage:
normalization: "RPKM"                             # Alterntively choose "RPGC", "CPM", "BPM". If you don't specify this argument, by default no normalization method will be used.

plotHeatmap:
refPointLabel: "TSS"                              # Specify the reference point label by yourself, e.g. "Center".

plotProfile:
colors: "red blue yellow green"                   # Please define colors of profile. The number of colors should be consistent with the number of samples.

plotCorrelation:
  corMethod: "pearson"                              # Alternatively "spearman" could be used.
  whatToPlot: "heatmap"                             # Alterntively "scatterplot" could be used.

Also, I found a mistake in config.yaml: binSize of bamCoverage is 50 by default, which is OK to use; what we want to change is the binSize of **computeMatrix**. So the parameters look like this:
bamCoverage:
  binSize: "50"

  .#  binSize parameters is set to 1000bp to test quickly the pipeline. Change to a lower value with real samples. 
  .#  computeMatrix
ComputeMatrix:
  GTF: "gencode.vM25.annotation.gtf"
  binSize: "1000"                                   # Test the pipelin with binSize=1000; please set it at a small number (e.g.10) when run it with real data.
