### ISSUE TITLE
Include documentation for the pipeline

### ISSUE THREAD

**Issue by JihedC** [JihedC/Snakemake_ATAC_2020#3]
Write a documentation in the READ.me

**Comment by JihedC** [comment]
Hi @WJH58 Did you have time to correct the documentation?

**Comment by WJH58** [comment]
@JihedC I modified the documentation. There are two things that I haven't done yet:
1. I didn't count the time of testing the pipeline because slurm is busy. 
2. I didn't write the output of testing pipeline. We've already have two parts showing the output: "Overview" and "Output description". I think the outputs of testing pipeline are the same.

**Comment by JihedC** [comment]
The documentation looks pretty good now! Good job!
